### ISSUE TITLE
Perco sdk library

### ISSUE THREAD

**Issue by Kazakoff64** [ProgRB/Staff#1]
Hi, can you lay out the Perco sdk library, if you can with examples of how it works?

**Comment by ProgRB** [comment]
Добрый день. По условиям предоставления SDK для предприятия  - библиотека и примеры являются конфиденциальными. Предоставить не могу

**Comment by Kazakoff64** [comment]
Хорошо, sdk нашел, подключил к Visual подключение есть списки получаю.
